server.port=${PORT:8080}
spring.application.name=booking-app

spring.datasource.url = ${DB_URL}
spring.datasource.username = ${DB_USERNAME}
spring.datasource.password = ${DB_PASSWORD}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

server.error.include-message=always
server.error.include-binding-errors=always
server.error.include-stacktrace=always

customer.service.url=${CUSTOMER_SERVICE_URL}